#!/usr/bin/env node

import { createHash } from "node:crypto";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const memoryDir = join(root, ".cursor", "memory");
const outputPath = join(memoryDir, "codebase.md");
const intentPath = join(memoryDir, "intent.md");
const checkOnly = process.argv.includes("--check");

const SOURCE_ROOTS = ["app", "components", "lib", "scripts"];
const SOURCE_EXT = new Set([".ts", ".tsx", ".js", ".mjs", ".css"]);
const IGNORE_DIRS = new Set([
  "node_modules",
  ".git",
  ".next",
  "agent-tools",
  "components/ui",
]);

function walk(dir, files = []) {
  if (!existsSync(dir)) {
    return files;
  }

  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    const rel = relative(root, full).replaceAll("\\", "/");

    if (entry.isDirectory()) {
      if (IGNORE_DIRS.has(entry.name) || IGNORE_DIRS.has(rel)) {
        continue;
      }
      walk(full, files);
      continue;
    }

    const ext = entry.name.slice(entry.name.lastIndexOf("."));
    if (SOURCE_EXT.has(ext)) {
      files.push(rel);
    }
  }

  return files;
}

function collectFiles() {
  const files = [];
  for (const dir of SOURCE_ROOTS) {
    walk(join(root, dir), files);
  }
  files.push("package.json", "README.md", "next.config.ts");
  return [...new Set(files)]
    .filter((file) => existsSync(join(root, file)))
    .sort();
}

function sha256(value) {
  return createHash("sha256").update(value).digest("hex");
}

function fileHash(rel) {
  return sha256(readFileSync(join(root, rel)));
}

function extractExports(source) {
  const names = new Set();
  const patterns = [
    /export\s+(?:async\s+)?function\s+([A-Za-z0-9_]+)/g,
    /export\s+(?:const|let|type|class)\s+([A-Za-z0-9_]+)/g,
    /export\s+\{([^}]+)\}/g,
  ];

  for (const pattern of patterns) {
    for (const match of source.matchAll(pattern)) {
      for (const part of match[1].split(",")) {
        const name = part.trim().split(/\s+as\s+/).at(-1)?.trim();
        if (name) {
          names.add(name);
        }
      }
    }
  }

  if (/export\s+default/.test(source)) {
    names.add("default");
  }

  return [...names].sort();
}

function extractRoutes() {
  const appDir = join(root, "app");
  if (!existsSync(appDir)) {
    return [];
  }

  const routes = [];

  function visit(dir, urlParts) {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const full = join(dir, entry.name);
      if (entry.isDirectory()) {
        if (entry.name === "api") {
          continue;
        }
        visit(full, [...urlParts, entry.name]);
        continue;
      }
      if (entry.name === "page.tsx" || entry.name === "page.ts") {
        const path = urlParts.length === 0 ? "/" : `/${urlParts.join("/")}`;
        routes.push(path);
      }
    }
  }

  visit(appDir, []);
  return routes.sort();
}

function summarizeFile(rel) {
  const source = readFileSync(join(root, rel), "utf8");
  const lines = source.split("\n").length;
  const bytes = statSync(join(root, rel)).size;
  const exported = extractExports(source);
  return { rel, lines, bytes, exported };
}

function renderTree(files) {
  const dirs = new Map();
  for (const file of files) {
    const folder = dirname(file);
    const list = dirs.get(folder) ?? [];
    list.push(file);
    dirs.set(folder, list);
  }

  return [...dirs.keys()]
    .sort()
    .map((folder) => {
      const label = folder === "." ? "." : folder;
      const children = dirs
        .get(folder)
        .map((file) => `  - \`${file.split("/").at(-1)}\``)
        .join("\n");
      return `- \`${label}/\`` + (children ? `\n${children}` : "");
    })
    .join("\n");
}

function buildMemory() {
  const files = collectFiles();
  const summaries = files.map(summarizeFile);
  const fingerprint = sha256(
    [
      ...files.map((file) => `${file}:${fileHash(file)}`),
      existsSync(intentPath)
        ? `intent:${fileHash(".cursor/memory/intent.md")}`
        : "intent:",
    ].join("\n")
  );
  const intent = existsSync(intentPath)
    ? readFileSync(intentPath, "utf8").trim()
    : "_No intent file._";
  const routes = extractRoutes();
  const libExports = summaries
    .filter((item) => item.rel.startsWith("lib/") && item.exported.length > 0)
    .map((item) => `- \`${item.rel}\`: ${item.exported.map((name) => `\`${name}\``).join(", ")}`)
    .join("\n");

  return `# Flick codebase memory

<!-- Generated by scripts/update-memory.mjs. Do not edit. -->
<!-- fingerprint:${fingerprint} -->

This file is the long-term memory of the git codebase. It is regenerated
from the working tree whenever \`npm run memory:update\` or the git hooks
run, so agents and humans can trust it over stale chat history.

## Intent

${intent}

## Snapshot

- **Source fingerprint:** \`${fingerprint.slice(0, 16)}\`
- **Tracked source files:** ${files.length}
- **Routes:** ${routes.map((route) => `\`${route}\``).join(", ") || "_none_"}

## Layout

${renderTree(files)}

## Library exports

${libExports || "_none_"}

## File index

| File | Lines | Exports |
| --- | ---: | --- |
${summaries
  .map((item) => {
    const exports = item.exported.length ? item.exported.join(", ") : "—";
    return `| \`${item.rel}\` | ${item.lines} | ${exports} |`;
  })
  .join("\n")}
`;
}

function normalize(value) {
  return value.replace(/\r\n/g, "\n").trim() + "\n";
}

const next = normalize(buildMemory());
mkdirSync(memoryDir, { recursive: true });

if (checkOnly) {
  if (!existsSync(outputPath)) {
    console.error("Codebase memory is missing. Run npm run memory:update.");
    process.exit(1);
  }
  const current = normalize(readFileSync(outputPath, "utf8"));
  if (current !== next) {
    console.error("Codebase memory is stale. Run npm run memory:update.");
    process.exit(1);
  }
  console.log("Codebase memory is current.");
  process.exit(0);
}

writeFileSync(outputPath, next);
console.log(`Updated ${relative(root, outputPath)}`);
